### ISSUE TITLE
morphhb or stepbible-data

### ISSUE THREAD

**Issue by anderson916** [openscriptures/morphhb#71]
Thanks for providing this wonderful resource. I am developing a quiz website for students of Biblical Hebrew. I see both this repository and 'stepbible-data' (https://github.com/tyndale/STEPBible-Data) providing full Hebrew bible and parsing information. I am wondering which is better, accurate, and updated. Thanks again.

**Comment by DavidTroidl** [comment]
The OHB on STEP began by using our data, before a sizeable portion of the parsing was completed. Since then the parsing was finished independently by each project, though we have kept in communication. Both projects are updated, when errors are identified, so I suppose it is a matter of opinion whose text is more accurate.
